name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Install Surge
        run: npm install --global surge

      - name: Run Tests
        run: npm test

      - name: Merge to Main and Deploy
        if: success()
        run: |
          # Additional steps for merging to main, if needed
          # git checkout main
          # git merge --no-ff ${{ github.sha }}

      - name: Deploy to Surge
        run: surge ./ --domain 20220018-final.surge.sh --token ${{ secrets.SURGE_TOKEN }}
        
      - name: Visit the website
        run: curl 20220018-final.surge.sh
